### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by Dan2552** [Dan2552/SublimeTextSwiftAutocomplete#11]

**Comment by Jax0rz** [comment]
Please Add this repo to Package Control

**Comment by Dan2552** [comment]
Sorry, didn't realise this had 👍 s on it.

Just updating to say I do intend to do this soon (probably at a lunchtime). If anybody else wants to give it a go in the meantime, feel free 😄

**Comment by Dan2552** [comment]
https://github.com/wbond/package_control_channel/pull/6862#pullrequestreview-87204911

**Comment by Dan2552** [comment]
🎉
